import { useMemo, useState } from 'react'
import { BriefcaseBusiness, Pencil, Plus, Trash2 } from 'lucide-react'
import { JOB_CHANNELS, JOB_INDUSTRIES, JOB_STATUSES } from '@/constants/jobs'
import { useCreateJob, useDeleteJob, useJobs, useUpdateJob } from '@/hooks/useJobs'
import type { JobEntry, JobStatus } from '@/types'

const today = () => new Date().toISOString().slice(0, 10)
type JobDraft = Omit<JobEntry, 'id' | 'createdAt' | 'updatedAt'>
const blank = (): JobDraft => ({ company: '', position: '', date: today(), status: 'applied', channel: '', industry: '', jdContent: '', jdImageIds: [], applyUrl: '', salary: '', deadline: null, notes: '' })

export function JobStation() {
  const { data: jobs = [], isLoading } = useJobs()
  const createJob = useCreateJob(); const updateJob = useUpdateJob(); const deleteJob = useDeleteJob()
  const [tab, setTab] = useState<'overview' | 'kanban'>('overview')
  const [draft, setDraft] = useState<JobDraft | null>(null)
  const [editingId, setEditingId] = useState<number | null>(null)
  const counts = useMemo(() => Object.fromEntries(JOB_STATUSES.map(({ key }) => [key, jobs.filter(j => j.status === key).length])), [jobs])
  const save = async () => { if (!draft?.company.trim() || !draft.position.trim()) return; if (editingId) await updateJob.mutateAsync({ id: editingId, ...draft }); else await createJob.mutateAsync(draft); setDraft(null); setEditingId(null) }
  const openEdit = (job: JobEntry) => { const { id, createdAt, updatedAt, ...data } = job; setEditingId(id); setDraft(data) }
  const set = (key: keyof JobDraft, value: JobDraft[keyof JobDraft]) => setDraft(current => current ? { ...current, [key]: value } as JobDraft : current)

  return <div className="h-full overflow-y-auto space-y-5 pb-24">
    <div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-milk-text flex items-center gap-2"><BriefcaseBusiness size={20}/>投递驿站</h2><p className="text-xs text-milk-text-muted mt-1">记录每一份投递与进展</p></div><button onClick={() => { setEditingId(null); setDraft(blank()) }} className="px-4 py-2 rounded-2xl bg-milk-primary text-white text-sm font-semibold flex gap-1"><Plus size={16}/>添加投递</button></div>
    <div className="flex gap-2">{(['overview','kanban'] as const).map(key => <button key={key} onClick={() => setTab(key)} className={`px-4 py-2 rounded-xl text-sm font-semibold ${tab === key ? 'bg-milk-primary text-white' : 'bg-white/50 text-milk-text-secondary'}`}>{key === 'overview' ? '总览' : '投递看板'}</button>)}</div>
    <div className="grid grid-cols-2 md:grid-cols-3 gap-3">{JOB_STATUSES.map(({key,label}) => <div key={key} className="rounded-2xl bg-white/50 p-4"><div className="text-xs text-milk-text-muted">{label}</div><div className="text-2xl font-bold text-milk-text mt-1">{counts[key]}</div></div>)}</div>
    {tab === 'overview' ? <div className="rounded-3xl bg-white/50 overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-milk-text-muted"><tr><th className="p-4">公司 / 岗位</th><th>状态</th><th>日期</th><th>渠道</th><th className="p-4">操作</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id} className="border-t border-milk-border/30"><td className="p-4"><b>{job.company}</b><div className="text-xs text-milk-text-muted">{job.position}</div></td><td>{JOB_STATUSES.find(s=>s.key===job.status)?.label}</td><td>{job.date}</td><td>{job.channel || '—'}</td><td className="p-4 flex gap-2"><button onClick={()=>openEdit(job)}><Pencil size={15}/></button><button onClick={()=>deleteJob.mutate(job.id)} className="text-red-500"><Trash2 size={15}/></button></td></tr>)}{!isLoading && jobs.length===0 && <tr><td colSpan={5} className="p-10 text-center text-milk-text-muted">暂无投递记录</td></tr>}</tbody></table></div> : <div className="grid grid-cols-1 md:grid-cols-3 gap-3">{JOB_STATUSES.map(status => <div key={status.key} className="rounded-2xl bg-white/40 p-3 min-h-36"><div className="text-sm font-bold mb-3">{status.label} · {counts[status.key]}</div>{jobs.filter(j=>j.status===status.key).map(job => <div key={job.id} className="bg-white/70 rounded-xl p-3 mb-2"><b className="text-sm">{job.company}</b><div className="text-xs text-milk-text-muted">{job.position}</div><select value={job.status} onChange={e=>updateJob.mutate({id:job.id,status:e.target.value as JobStatus})} className="mt-2 w-full text-xs bg-transparent"><option value={job.status}>移动到…</option>{JOB_STATUSES.filter(s=>s.key!==job.status).map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></div>)}</div>)}</div>}
    {draft && <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/20" onClick={()=>setDraft(null)}/><div className="relative bg-white rounded-3xl p-6 w-full max-w-lg space-y-3 max-h-[80vh] overflow-y-auto"><h3 className="font-bold">{editingId ? '编辑投递' : '添加投递'}</h3><input value={draft.company} onChange={e=>set('company',e.target.value)} placeholder="公司名称 *" className="w-full p-3 rounded-xl border"/><input value={draft.position} onChange={e=>set('position',e.target.value)} placeholder="岗位名称 *" className="w-full p-3 rounded-xl border"/><input type="date" value={draft.date} onChange={e=>set('date',e.target.value)} className="w-full p-3 rounded-xl border"/><select value={draft.status} onChange={e=>set('status',e.target.value as JobStatus)} className="w-full p-3 rounded-xl border">{JOB_STATUSES.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select><select value={draft.channel} onChange={e=>set('channel',e.target.value)} className="w-full p-3 rounded-xl border"><option value="">投递渠道</option>{JOB_CHANNELS.map(x=><option key={x}>{x}</option>)}</select><select value={draft.industry} onChange={e=>set('industry',e.target.value)} className="w-full p-3 rounded-xl border"><option value="">行业</option>{JOB_INDUSTRIES.map(x=><option key={x}>{x}</option>)}</select><textarea value={draft.notes} onChange={e=>set('notes',e.target.value)} placeholder="备注" className="w-full p-3 rounded-xl border"/><div className="flex gap-3"><button onClick={()=>setDraft(null)} className="flex-1 p-3">取消</button><button onClick={save} className="flex-1 p-3 rounded-xl bg-milk-primary text-white">保存</button></div></div></div>}
  </div>
}
